Repository ojasaklechayt/Music-Streaming-App, pull requests merged in 2023-10, with the labels that each got.

#3 adding-CODE_OF_CONDUCT.md-updating-CONTRIBUTION.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#7 Feat middleware
  frontend/middleware.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 updated readme file
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#11 Fix: Fixed Register signup process and login signin process
  frontend/app/register/page.js
Labels: hacktoberfest, hacktoberfest-accepted

#15 Fix cookie not being saved
  backend/controllers/userController.js
  backend/index.js
  backend/middleware.js
  frontend/app/login/page.js
  frontend/app/register/page.js
  frontend/package-lock.json
  frontend/package.json
Labels: bug, hacktoberfest, hacktoberfest-accepted

#20 Added Page Title And Icon
  frontend/app/favicon.ico
  frontend/app/layout.js
Labels: hacktoberfest, hacktoberfest-accepted

#23 Update README.md file
  README.md
  app.png
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#30 [feat] [client] Adding-toast-notifications
  backend/controllers/userController.js
  frontend/app/login/page.js
  frontend/app/register/page.js
  frontend/package-lock.json
  frontend/package.json
Labels: hacktoberfest, hacktoberfest-accepted
